name: voice_banking_poc
description: Voice Banking PoC Flutter App
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter: 
    sdk: flutter
  record: ^6.1.1
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  dio: ^5.5.0+1
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  flutter_tts: ^4.2.3
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0

flutter: 
  uses-material-design: true
  generate: true

generate:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart

# Version information for App Store
version: 1.0.1+6
